### ISSUE TITLE
ImportError: cannot import name 'BosonNLP'

### ISSUE THREAD

**Issue by zzzeven** [bosondata/bosonnlp.py#10]
I have already install the package.
Use pip install bosonnlp.
Why does show 'ImportError: cannot import name 'BosonNLP'

**Comment by mrluanma** [comment]
You cann't name you own module bosonnlp.py.

**Comment by zzzeven** [comment]
# -*- coding: utf-8 -*-
from __future__ import print_function, unicode_literals
from bosonnlp import BosonNLP

nlp = BosonNLP('YOUR_API_TOKEN')
print(nlp.sentiment('大众深陷断轴门事件'))

but the sample code is that using.

**Comment by zzzeven** [comment]
When I used CLI python, it's fine.
But in pycharm IDE, it will show "ImportError: cannot import name 'BosonNLP'"

**Comment by messense** [comment]
It's not an issue of bosonnlp.py. Please refer to Jetbrains PyCharm documentation for how to configure Python interpreter.

https://www.jetbrains.com/help/pycharm/configuring-language-interpreter.html
