### ISSUE TITLE
Should  Class BosonNLP increase a http proxy

### ISSUE THREAD

**Issue by daohu527** [bosondata/bosonnlp.py#5]
I have use a HTTP proxy, and when I use Class BosonNLP to process a text, it return an error below:
Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0228DA30>: Failed to establish a new connection: [Errno 10060] ',)

Could you add a HTTP proxy param to the Class BosonNLP

**Comment by messense** [comment]
https://github.com/bosondata/bosonnlp.py/pull/6
